apiVersion: apps/v1
kind: Deployment
metadata:
  name: devs-outstaff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devs-outstaff
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: devs-outstaff
    spec:
      containers:
      - name: devs-outstaff
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m