# Generated by Django 3.2.3 on 2021-06-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210602_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entriesstatistics',
            name='amount_of_entries',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entriesstatistics',
            name='week_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
