# Generated by Django 3.2.3 on 2021-06-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_entries_week_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='week_number',
        ),
    ]
