# Generated by Django 3.2 on 2021-05-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedproduct',
            options={'verbose_name': 'OrderedProduct (Cart)', 'verbose_name_plural': 'OrderedProducts (Cart)'},
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
