# Generated by Django 3.2 on 2021-05-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210425_1100'),
        ('shop', '0005_auto_20210504_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedProduct',
            new_name='Cart',
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Cart'},
        ),
    ]
