# Generated by Django 3.2 on 2021-05-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210505_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Tag'),
        ),
    ]
