# Generated by Django 3.2 on 2021-05-05 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210425_1100'),
        ('shop', '0009_alter_order_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdata',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.profile'),
        ),
    ]
