# Generated by Django 3.2 on 2021-05-05 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210505_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_data', to='shop.billingdata'),
        ),
    ]
