# Generated by Django 3.2 on 2021-05-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210505_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberoforder',
            name='number',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
