# Generated by Django 3.2 on 2021-05-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproductsafterdeleting',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderedproductsafterdeleting',
            name='product',
        ),
        migrations.DeleteModel(
            name='NumberOfOrder',
        ),
        migrations.DeleteModel(
            name='OrderedProductsAfterDeleting',
        ),
    ]
