# Generated by Django 3.2 on 2021-05-06 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210506_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='copy_of_product',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='copy_of_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
    ]
