# Generated by Django 3.2 on 2021-05-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_order_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_products',
            new_name='ordered_product',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='order_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
