# Generated by Django 3.2 on 2021-06-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_product',
            field=models.ManyToManyField(to='shop.OrderedProduct'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(blank=True, to='shop.Tag'),
        ),
    ]
